**American Express Data Analysis Project**

## Importing libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
tf.__version__

'2.15.0'

## Importing dataset

In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/PREPINSTA DATA ANYLITICS INTERSHIP PROJECTS /PROJECTS /AMERICAN EXPRESS PROJECT /DATASET /Dataset_master.xlsx - American Express User Exit Pred.csv')
X = dataset.iloc[:, 0:-1].values
y = dataset.iloc[:, -1].values

In [5]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


## Encoding categorical data

### Gender column : Label Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:, 2] = label_encoder.fit_transform(X[:, 2])

In [7]:
print(X)

[[553 'Delhi' 0 ... 4 1 274150]
 [447 'Bengaluru' 1 ... 4 1 519360]
 [501 'Delhi' 0 ... 4 1 545501]
 ...
 [627 'Mumbai' 0 ... 4 0 494067]
 [600 'Bengaluru' 0 ... 2 1 109375]
 [553 'Delhi' 1 ... 4 1 180031]]


### Geography column : One hot Encoding

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


## Splitting dataset into Training & Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## ANN

### Initialization

In [12]:
ann = tf.keras.models.Sequential()

### Adding input layer and first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## ANN Training

### Compiling ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training on training dataset

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 120)

Epoch 1/120
249/249 [==============================] - 2s 2ms/step - loss: 0.6298 - accuracy: 0.7065
Epoch 2/120
249/249 [==============================] - 0s 2ms/step - loss: 0.5063 - accuracy: 0.7957
Epoch 3/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4571 - accuracy: 0.7971
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4363 - accuracy: 0.7993
Epoch 5/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4228 - accuracy: 0.8087
Epoch 6/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4133 - accuracy: 0.8166
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4071 - accuracy: 0.8228
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8260
Epoch 9/120
249/249 [==============================] - 0s 2ms/step - loss: 0.3994 - accuracy: 0.8238
Epoch 10/120
249/249 [==============================] - 0s 2ms/step - loss: 0.3970 - accura

# Predictions

### Single Prediction

In [18]:
print(ann.predict(sc.transform([[0.0, 1.0, 0.0, 501, 0, 32, 2, 0.0, 4, 1, 545501]])) > 0.5)

1/1 [==============================] - 0s 98ms/step
[[False]]


### Predication on testset

In [19]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [1 1]]


### Confusion Matrix

In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   61]
 [ 228  185]]


0.8544813695871097